AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket holding lambda functions
Parameters:
  BucketName:
    Type: String
    Description: Name of the bucket in which lambda functions will be stored
Resources:
  LambdaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
